### ISSUE TITLE
Amazon s3a returns 400 Bad Request with Spark

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/modern-data-analytics-stack#19]
If you'd like to anyway use the region that supports Signature V4 in spark you can pass flag `-Dcom.amazonaws.services.s3.enableV4` to the driver options and executor options on runtime. For example:

```
spark-submit --conf spark.driver.extraJavaOptions='-Dcom.amazonaws.services.s3.enableV4' \
    --conf spark.executor.extraJavaOptions='-Dcom.amazonaws.services.s3.enableV4' \
    ... (other spark options)
```

With this settings Spark is able to write to Frankfurt (and other V4-only regions) even with not-so-fresh AWS sdk version (`com.amazonaws:aws-java-sdk:1.7.4` in my case)

**Comment by gschmutz** [comment]
**For Spark:**

set these two properties in `spark-defaults.conf`

```
spark.driver.extraJavaOptions    -Dcom.amazonaws.services.s3.enableV4
spark.executor.extraJavaOptions  -Dcom.amazonaws.services.s3.enableV4
```

**For Zeppelin: **

set the environment variable in Zeppelin container:

```
SPARK_SUBMIT_OPTIONS: "--conf spark.driver.extraJavaOptions=-Dcom.amazonaws.services.s3.enableV4 --conf spark.executor.extraJavaOptions=-Dcom.amazonaws.services.s3.enableV4"
```

**Comment by josiahjohnston** [comment]
This was a great help; thanks for sharing. I was banging my head on this; for me it worked in all US regions except Ohio (us-east-2). 
To get things working, I ended up combining your advise & this post: https://stackoverflow.com/a/57381459/2872820
Core changes were just in Zeppelin's spark interpreter settings:
* spark.driver.extraJavaOptions    -Dcom.amazonaws.services.s3.enableV4
* spark.executor.extraJavaOptions  -Dcom.amazonaws.services.s3.enableV4
* spark.hadoop.fs.s3a.endpoint s3.us-east-2.amazonaws.com
